import Fettuccine.Divide
import Fettuccine.CMonomialOrder
import Fettuccine.CMvPolynomial
import Mathlib.RingTheory.Ideal.Basic

/-!
# Buchberger's Theorem

This file defines Buchberger's algorithm for computing Gröbner bases for ideals of
`CMvPolynomial σ R`.

## Definitions

* `sPolynomial f g` : the S-polynomial of two polynomials `f` and `g`.
-/

section SPolynomial

variable {σ : Type*} [DecidableEq σ] (ord : CMonomialOrder σ)
variable {R : Type*} [DecidableEq R] [CommRing R]

namespace CMvPolynomial

/-- The **S-polynomial** of two polynomials, with respect to the monomial order `ord`, as defined by
    Buchberger. -/
def sPolynomial (f g : CMvPolynomial σ R) : CMvPolynomial σ R :=
  let l := CMonomial.lcm (in[ord](f)) (in[ord](g))
  -- Each leading monomial divides their lowest common multiple, so the quotients exist.
  have hf : (l.divide (in[ord](f))).isSome := by
    have hdiv : CMonomial.divides? (in[ord](f)) l :=
      CMonomial.divides?_lcm_left (in[ord](f)) (in[ord](g))
    simp [CMonomial.divide, hdiv]
  have hg : (l.divide (in[ord](g))).isSome := by
    have hdiv : CMonomial.divides? (in[ord](g)) l :=
      CMonomial.divides?_lcm_right (in[ord](f)) (in[ord](g))
    simp [CMonomial.divide, hdiv]
  -- Use those quotients to scale f and g to a common leading monomial, and then subtract.
  let mf := Option.get (l.divide (in[ord](f))) hf
  let mg := Option.get (l.divide (in[ord](g))) hg
  CMvPolynomial.ofMonomial mf (leadingCoefficient ord g) * f -
    CMvPolynomial.ofMonomial mg (leadingCoefficient ord f) * g

end CMvPolynomial

end SPolynomial

variable {σ : Type*} [DecidableEq σ] (ord : CMonomialOrder σ)
variable {R : Type*} [DecidableEq R] [Field R]

namespace CMvPolynomial

/-- The initial ideal of a set of polynomials with respect to `ord`, generated by their leading
    monomials. -/
def initialIdeal' (S : Set (CMvPolynomial σ R)) : Ideal (CMvPolynomial σ R) :=
  Ideal.span { m | ∃ f ∈ S, m = CMvPolynomial.ofMonomial (in[ord](f)) (1 : R) }

/-- The initial ideal of an ideal with respect to `ord`, generated by the leading monomials of all
    of its elements. -/
def initialIdeal (I : Ideal (CMvPolynomial σ R)) : Ideal (CMvPolynomial σ R) :=
  initialIdeal' (ord := ord) (I : Set (CMvPolynomial σ R))

/-- Mathematical Groebner basis predicate: `G` lies in `I` and has the same initial ideal as `I`.
    Here `G` is represented as a finite list. -/
def IsGroebnerBasis (I : Ideal (CMvPolynomial σ R)) (G : List (CMvPolynomial σ R)) : Prop :=
  (∀ g ∈ G, g ∈ I) ∧
    initialIdeal' (ord := ord) {g | g ∈ G} = initialIdeal (ord := ord) I
private structure ReductionData (G : List (CMvPolynomial σ R)) : Prop where
  nonzero : ∀ g ∈ G, g ≠ 0

/-- Computational Groebner basis predicate: `G` lies in `I`, is nonempty/nonzero, and every
    S-polynomial of pairs in `G` reduces to zero modulo `G`. -/
def IsGroebnerBasis₁ (I : Ideal (CMvPolynomial σ R)) (G : List (CMvPolynomial σ R)) : Prop :=
  (∀ g ∈ G, g ∈ I) ∧
    ∃ hG : ReductionData G,
      ∀ f ∈ G, ∀ g ∈ G,
        (CMvPolynomial.mvDivideₙ (ord := ord)
          (f := CMvPolynomial.sPolynomial (ord := ord) f g)
          (gs := G)
          hG.nonzero).2 = 0

/-- Buchberger's theorem: the initial-ideal characterization of Groebner bases is equivalent to
    the S-polynomial reduction characterization. -/
theorem buchberger (I : Ideal (CMvPolynomial σ R)) (G : List (CMvPolynomial σ R)) :
    IsGroebnerBasis ord I G ↔ IsGroebnerBasis₁ ord I G := by
  sorry

/-- Safe list indexing by `Nat`. -/
private def listGet? {α : Type*} : List α → Nat → Option α
  | [], _ => none
  | a :: _, 0 => some a
  | _ :: as, n + 1 => listGet? as n

/-- Initial queue of S-pairs `(i, j)` with `0 ≤ i < j < n`. -/
private def pairQueue (n : Nat) : List (Nat × Nat) :=
  (List.range n).foldl
    (fun acc j => acc ++ (List.range j).map (fun i => (i, j)))
    []

/-- Naive Buchberger algorithm:
    start from generators, process all S-pairs, reduce each S-polynomial by the current basis, and
    append non-zero remainders.

    The recursion is explicitly fuel-bounded so Lean can verify termination structurally. -/
def buchberger_groebnerBasis (gens : List (CMvPolynomial σ R)) (maxSteps : Nat := 512) :
    List (CMvPolynomial σ R) :=
  let basis0 := gens.filter (fun g => g ≠ 0)
  let pairs0 := pairQueue basis0.length
  let hBasis0_nz : ∀ g ∈ basis0, g ≠ 0 := by
    intro g hg
    simpa using (List.mem_filter.mp hg).2
  let rec loop (fuel : Nat) (basis : List (CMvPolynomial σ R))
      (hBasis_nz : ∀ g ∈ basis, g ≠ 0) (pairs : List (Nat × Nat)) : List (CMvPolynomial σ R) :=
    match fuel with
    | 0 => basis
    | fuel + 1 =>
        match pairs with
        | [] => basis
        | (i, j) :: rest =>
            match hfi : listGet? basis i, hgj : listGet? basis j with
            | some f, some g =>
                let s := CMvPolynomial.sPolynomial (ord := ord) f g
                let r := (CMvPolynomial.mvDivideₙ (ord := ord)
                  (f := s) (gs := basis) hBasis_nz).2
                if hr : r = 0 then
                  loop fuel basis hBasis_nz rest
                else
                  let newIdx := basis.length
                  let basis' := basis ++ [r]
                  let hBasis'_nz : ∀ g ∈ basis', g ≠ 0 := by
                    intro g hg
                    rw [List.mem_append] at hg
                    rcases hg with hgin | hgin
                    · exact hBasis_nz g hgin
                    · simp at hgin
                      simpa [hgin] using hr
                  let pairs' := rest ++ (List.range newIdx).map (fun k => (k, newIdx))
                  loop fuel basis' hBasis'_nz pairs'
            | _, _ =>
                loop fuel basis hBasis_nz rest
  loop maxSteps basis0 hBasis0_nz pairs0

def buchbergerAlgorithm (gens : List (CMvPolynomial σ R)) (maxSteps : Nat := 512) :
    List (CMvPolynomial σ R) :=
  buchberger_groebnerBasis (ord := ord) gens maxSteps

end CMvPolynomial
