import Fettuccine.Division
import Fettuccine.CMonomialOrder
import Mathlib.RingTheory.Ideal.Basic

/-!
# Gröbner Bases

This file defines the notion of a Gröbner basis of an ideal of `CMvPolynomial σ R`, phrased in terms
of Buchberger's criterion.

## Definitions

* `CMvPolynomial.sPolynomial ord f g` : the S-polynomial of `f` and `g`.
* `Groebner.linearCombination gs qs` : the linear combination `∑ᵢ gsᵢ * qsᵢ`.
* `Groebner.ReducesToZero tag f gs` : `f` reduces to zero modulo `gs`.
* `Groebner.IsGroebnerBasis tag I basis` : the statement of Buchberger's characterization of Gröbner
  bases, with respect to the monomial order selected by `tag`.
-/

open CMonomialOrder
open scoped CMonomialOrder

namespace CMvPolynomial

variable {σ : Type*} [DecidableEq σ]
variable {R : Type*} [DecidableEq R] [Field R]
variable (ord : CMonomialOrder σ)

/-- The **S-polynomial** of `f` and `g` with respect to the monomial order `ord`. -/
def sPolynomial (f g : CMvPolynomial σ R) : CMvPolynomial σ R :=
  let lm_f := in[ord](f)
  let lm_g := in[ord](g)
  -- These divisions always succeed, since the lowest common multiple is always divisible by both
  -- its factors.
  let γ   := CMonomial.lcm lm_f lm_g
  let mf  := (CMonomial.div γ lm_f).getD 0
  let mg  := (CMonomial.div γ lm_g).getD 0
  ofMonomial mf (leadingCoefficient ord g) * f - ofMonomial mg (leadingCoefficient ord f) * g

/-- The S-polynomial, computed using `leadingMonomial'` and `leadingCoefficient'`. -/
@[inline] def sPolynomial' (f g : CMvPolynomial σ R) : CMvPolynomial σ R :=
  let lm_f := in'[ord](f)
  let lm_g := in'[ord](g)
  let γ   := CMonomial.lcm lm_f lm_g
  let mf  := (CMonomial.div γ lm_f).getD 0
  let mg  := (CMonomial.div γ lm_g).getD 0
  ofMonomial mf (leadingCoefficient' ord g) * f - ofMonomial mg (leadingCoefficient' ord f) * g

/-- The definitions of the S-polynomial coincide. -/
lemma sPolynomial_eq_sPolynomial' (f g : CMvPolynomial σ R) :
    sPolynomial ord f g = sPolynomial' ord f g := by
  simp [sPolynomial, sPolynomial', leadingCoefficient, leadingCoefficient',
    leadingMonomial_eq_leadingMonomial']

end CMvPolynomial

namespace Groebner

universe u v

variable {σ : Type u} [DecidableEq σ]
variable {R : Type*} [DecidableEq R] [Field R]
variable {tag : Type v}

/-- The monomial order selected by a type-level tag. -/
private abbrev taggedOrder (tag : Type v) [CMonomialOrder.CMonomialOrderTag tag σ] :
    CMonomialOrder σ :=
  CMonomialOrder.CMonomialOrderTag.ord (tag := tag) (σ := σ)

/-- A polynomial linear combination, truncating if the lists have different lengths. -/
def linearCombination : List (CMvPolynomial σ R) → List (CMvPolynomial σ R) → CMvPolynomial σ R
  | [], _ => 0
  | _, [] => 0
  | g :: gs, q :: qs => g * q + linearCombination gs qs

/-- `qs` witnesses that `f` reduces to zero modulo `gs` under `ord`. -/
def ReducesToZeroWith (tag : Type v) [CMonomialOrder.CMonomialOrderTag tag σ]
    (f : CMvPolynomial σ R)
    (gs qs : List (CMvPolynomial σ R)) : Prop :=
  qs.length = gs.length ∧
    f = linearCombination gs qs ∧
      ∀ gq ∈ List.zip gs qs,
        (taggedOrder tag).toSyn (CMvPolynomial.leadingMonomial' (taggedOrder tag) (gq.1 * gq.2)) ≤
          (taggedOrder tag).toSyn (CMvPolynomial.leadingMonomial' (taggedOrder tag) f)

/-- `f` reduces to zero modulo `gs` under `ord`. -/
def ReducesToZero
    (tag : Type v) [CMonomialOrder.CMonomialOrderTag tag σ]
    (f : CMvPolynomial σ R)
    (gs : List (CMvPolynomial σ R)) : Prop :=
  ∃ qs : List (CMvPolynomial σ R), ReducesToZeroWith tag f gs qs

/-- The ideal generated by a list of polynomials. -/
def idealOf (I : List (CMvPolynomial σ R)) : Ideal (CMvPolynomial σ R) :=
  Ideal.span { f | f ∈ I }

/-- The mathematically clean C-level Buchberger criterion. -/
def IsGroebnerBasis (tag : Type v) [CMonomialOrder.CMonomialOrderTag tag σ]
    (I : List (CMvPolynomial σ R))
    (basis : List (CMvPolynomial σ R)) : Prop :=
  (∀ i : Fin basis.length, basis.get i ∈ idealOf I) ∧
    ∀ i j : Fin basis.length, i < j →
      ReducesToZero tag
        (CMvPolynomial.sPolynomial' (taggedOrder tag) (basis.get i) (basis.get j)) basis

omit [DecidableEq R] in
/-- A linear combination of ideal generators lies in the ideal. -/
lemma linearCombination_mem_idealOf (I : List (CMvPolynomial σ R))
    (coeffs : List (CMvPolynomial σ R)) :
    linearCombination I coeffs ∈ idealOf I := by
  induction I generalizing coeffs with
  | nil =>
    cases coeffs <;> simp [linearCombination, idealOf]
  | cons g I ih =>
    cases coeffs with
    | nil           => simp [linearCombination, idealOf]
    | cons c coeffs =>
      -- FIXME: This proof was written with a lot of help from AI, and is pretty unreadable. Can we
      -- clean it up a bunch?
      simp only [linearCombination]
      apply Ideal.add_mem
      · have hg_span : g ∈ Ideal.span ({ f | f ∈ g :: I } : Set (CMvPolynomial σ R)) :=
          Ideal.subset_span
            (show g ∈ ({ f | f ∈ g :: I } : Set (CMvPolynomial σ R)) by simp)
        exact Ideal.mul_mem_right c _ hg_span
      · exact Ideal.span_mono (by intro f hf; exact List.mem_cons_of_mem g hf) (ih coeffs)

theorem ReducesToZero_nil_iff [CMonomialOrder.CMonomialOrderTag tag σ]
    (f : CMvPolynomial σ R) : ReducesToZero tag f [] ↔ f = 0 := by
  constructor
  · rintro ⟨qs, h_len, h_eq, -⟩
    cases qs with
    | nil       => simpa [linearCombination] using h_eq
    | cons q qs => simp at h_len
  · intro hf
    exact ⟨[], by simp [ReducesToZeroWith, linearCombination, hf]⟩

omit [DecidableEq R] in
/-- The ideal generated by the empty set is the zero ideal. -/
@[simp] lemma idealOf_nil : idealOf ([] : List (CMvPolynomial σ R)) = ⊥ := by
  simp [idealOf]

omit [DecidableEq R] in
/-- A generator of the ideal is in the ideal. -/
theorem mem_idealOf_cons {g : CMvPolynomial σ R} {I : List (CMvPolynomial σ R)} :
    g ∈ idealOf (g :: I) := by
  exact Ideal.subset_span (by simp)

end Groebner
