import Fettuccine.Division
import Fettuccine.CMonomialOrder
import Mathlib.RingTheory.Ideal.Basic

/-!
# Gröbner Bases

This file defines the notion of a Gröbner basis of an ideal of `CMvPolynomial σ R`, phrased in terms
of Buchberger's criterion.

## Definitions

* `CMvPolynomial.sPolynomial ord f g` : the S-polynomial of `f` and `g`.
* `CMvPolynomial.sPolynomial' ord f g` : a computation-friendly S-polynomial.
* `Groebner.linearCombination gs qs` : the linear combination `∑ᵢ gsᵢ * qsᵢ`.
* `Groebner.ReducesToZero tag f gs` : `f` reduces to zero modulo `gs`.
* `Groebner.IsGroebnerBasis tag I basis` : Buchberger's criterion plus ideal membership.
-/

open CMonomialOrder
open scoped CMonomialOrder

namespace CMvPolynomial

variable {σ : Type*} [DecidableEq σ]
variable {R : Type*} [DecidableEq R] [Field R]
variable (ord : CMonomialOrder σ)

/-- The **S-polynomial** of `f` and `g` with respect to the monomial order `ord`. -/
def sPolynomial (f g : CMvPolynomial σ R) : CMvPolynomial σ R :=
  let lm_f := in[ord](f)
  let lm_g := in[ord](g)
  -- These divisions always succeed, since the lowest common multiple is always divisible by both
  -- its factors.
  let γ   := CMonomial.lcm lm_f lm_g
  let mf  := (CMonomial.div γ lm_f).getD 0
  let mg  := (CMonomial.div γ lm_g).getD 0
  ofMonomial mf (leadingCoefficient ord g) * f - ofMonomial mg (leadingCoefficient ord f) * g

/-- The S-polynomial, computed using `leadingMonomial'` and `leadingCoefficient'`. -/
@[inline] def sPolynomial' (f g : CMvPolynomial σ R) : CMvPolynomial σ R :=
  let lm_f := in'[ord](f)
  let lm_g := in'[ord](g)
  let γ   := CMonomial.lcm lm_f lm_g
  let mf  := (CMonomial.div γ lm_f).getD 0
  let mg  := (CMonomial.div γ lm_g).getD 0
  ofMonomial mf (leadingCoefficient' ord g) * f - ofMonomial mg (leadingCoefficient' ord f) * g

theorem sPolynomial_eq_sPolynomial' (f g : CMvPolynomial σ R) :
    sPolynomial ord f g = sPolynomial' ord f g := by
  simp [sPolynomial, sPolynomial', leadingMonomial_eq_leadingMonomial' ord f,
    leadingMonomial_eq_leadingMonomial' ord g, leadingCoefficient, leadingCoefficient']

end CMvPolynomial

namespace Groebner

universe u v

variable {σ : Type u} [DecidableEq σ]
variable {R : Type*} [DecidableEq R] [Field R]
variable {tag : Type v}

/-- The monomial order selected by a type-level tag. -/
private abbrev taggedOrder (tag : Type v) [CMonomialOrder.CMonomialOrderTag tag σ] :
    CMonomialOrder σ :=
  CMonomialOrder.CMonomialOrderTag.ord (tag := tag) (σ := σ)

/-- A polynomial linear combination, truncating if the lists have different lengths. -/
def linearCombination :
    List (CMvPolynomial σ R) → List (CMvPolynomial σ R) → CMvPolynomial σ R
  | [], _ => 0
  | _, [] => 0
  | g :: gs, q :: qs => g * q + linearCombination gs qs

/-- `qs` witnesses that `f` reduces to zero modulo `gs` under `ord`. -/
def ReducesToZeroWith
    (tag : Type v) [CMonomialOrder.CMonomialOrderTag tag σ]
    (f : CMvPolynomial σ R)
    (gs qs : List (CMvPolynomial σ R)) : Prop :=
  qs.length = gs.length ∧
  f = linearCombination gs qs ∧
  ∀ gq ∈ List.zip gs qs,
    (taggedOrder tag).toSyn (CMvPolynomial.leadingMonomial' (taggedOrder tag) (gq.1 * gq.2)) ≤
      (taggedOrder tag).toSyn (CMvPolynomial.leadingMonomial' (taggedOrder tag) f)

/-- `f` reduces to zero modulo `gs` under `ord`. -/
def ReducesToZero
    (tag : Type v) [CMonomialOrder.CMonomialOrderTag tag σ]
    (f : CMvPolynomial σ R)
    (gs : List (CMvPolynomial σ R)) : Prop :=
  ∃ qs : List (CMvPolynomial σ R), ReducesToZeroWith tag f gs qs

/-- The ideal generated by a list of polynomials. -/
def idealOf (I : List (CMvPolynomial σ R)) : Ideal (CMvPolynomial σ R) :=
  Ideal.span { f | f ∈ I }

/-- The mathematically clean C-level Buchberger criterion. -/
def IsGroebnerBasis
    (tag : Type v) [CMonomialOrder.CMonomialOrderTag tag σ]
    (I : List (CMvPolynomial σ R))
    (basis : List (CMvPolynomial σ R)) : Prop :=
  (∀ i : Fin basis.length, basis.get i ∈ idealOf I) ∧
  ∀ i j : Fin basis.length, i < j →
    ReducesToZero tag
      (CMvPolynomial.sPolynomial' (taggedOrder tag) (basis.get i) (basis.get j)) basis

omit [DecidableEq R] in
lemma linearCombination_mem_idealOf
    (gens coeffs : List (CMvPolynomial σ R)) :
    linearCombination gens coeffs ∈ idealOf gens := by
  induction gens generalizing coeffs with
  | nil =>
      cases coeffs <;> simp [linearCombination, idealOf]
  | cons g gens ih =>
      cases coeffs with
      | nil =>
          simp [linearCombination, idealOf]
      | cons c coeffs =>
          simp only [linearCombination]
          apply Ideal.add_mem
          · have hgspan : g ∈ Ideal.span
                ({ f | f ∈ g :: gens } : Set (CMvPolynomial σ R)) :=
              Ideal.subset_span
                (show g ∈ ({ f | f ∈ g :: gens } : Set (CMvPolynomial σ R)) by simp)
            exact Ideal.mul_mem_right c _ hgspan
          · exact Ideal.span_mono (by intro f hf; exact List.mem_cons_of_mem g hf) (ih coeffs)

end Groebner
