import Fettuccine.Algorithm.Groebner
import Mathlib.Algebra.Field.Rat

/-!
# Buchberger's Algorithm

This file implements Buchberger's algorithm for the computation of Gröbner bases of ideals of
`FMvPolynomial n R`.

## Definitions

* `buchberger' ord gens (fuel)` : computes a Gröbner basis for the ideal generated by `gens` with
  respect to the monomial order `ord`, constrained by `fuel` (default: 2048).
* `buchberger ord gens (fuel)` : computes a Gröbner basis for the ideal generated by `gens` with
  respect to the monomial order `ord` and **certifies the basis**, constrained by `fuel`.
-/

namespace FMvPolynomial

variable {n : ℕ}
variable {R : Type*} [DecidableEq R] [Zero R] [AddGroup R] [DivisionRing R]

/-- **Buchberger's algorithm** for computing a Gröbner basis, uncertified. -/
def buchberger' (ord : FMonomialOrder n) (gens : Array (FMvPolynomial n R))
    -- Again, this should be enough fuel.
    (fuel : ℕ := 2048) : Array (FMvPolynomial n R) :=
  -- Initially, the basis consists of the (non-zero) generators and we consider each pair.
  let basis₀ : Array (FMvPolynomial n R) :=
    (gens.map normalize).filter fun g => g.size > 0
  let queue₀ : List (ℕ × ℕ) :=
    (List.range basis₀.size).foldl
      (fun pairs j => pairs ++ (List.range j).map (fun i => (i, j)))
      []
  loop fuel basis₀ queue₀
where
  /-- Process one pair `(i, j)` and return the updated basis and remaining queue. -/
  loopOne (basis : Array (FMvPolynomial n R)) (queue : List (ℕ × ℕ)) (i j : ℕ) :
      Array (FMvPolynomial n R) × List (ℕ × ℕ) :=
    match basis[i]?, basis[j]? with
    | none, _
    | _, none        => (basis, queue)
    | some f, some g =>
      match f[0]?, g[0]? with
      | none, _
      | _, none                      => (basis, queue)
      | some (lm_f, _), some (lm_g, _) =>
        if FMonomial.relativelyPrime? lm_f lm_g then
          -- If the leading monomials are relatively prime, the S-polynomial automatically reduces
          -- to zero regardless of the monomial order. Useful!
          (basis, queue)
        else
          let (_, r) := mvDivide ord (sPolynomial ord f g) basis
          if r.size == 0 then
            (basis, queue)
          else
            let i      := basis.size
            let queue₁ := queue ++ (List.range i).map (·, i)
            (basis.push r, queue₁)
  /-- Iterate through the queue until fuel is exhausted or the queue is empty. -/
  loop (fuel : ℕ) (basis : Array (FMvPolynomial n R)) (queue : List (ℕ × ℕ)) :
      Array (FMvPolynomial n R) :=
    match fuel with
    | 0        => basis -- probably wrong
    | fuel + 1 =>
      match queue with
      | []               => basis -- done
      | (i, j) :: queue' =>
        let (basis₁, queue₁) := loopOne basis queue' i j
        loop fuel basis₁ queue₁

section Certification

/-- A polynomial coefficient vector, implicitly indexed by the original generators. -/
structure CoefficientVector (n' : ℕ) (n : ℕ) (R : Type*) where
  vec : Array (FMvPolynomial n R)
  hsize : vec.size = n'
deriving DecidableEq

namespace CoefficientVector

/-- The zero vector of dimension `m`. -/
def zero (n' n : ℕ) : CoefficientVector n' n R :=
  ⟨Array.replicate n' #[], by simp⟩

/-- The i-th "standard basis vector". -/
def unit (n' n : ℕ) (i : Fin n') : CoefficientVector n' n R :=
  ⟨(Array.replicate n' #[]).set i #[(FMonomial.zero n, 1)], by simp⟩

/-- Vector addition. -/
def add (a b : CoefficientVector n' n R) : CoefficientVector n' n R :=
  ⟨Array.zipWith FMvPolynomial.add a.vec b.vec, by simp [a.hsize, b.hsize]⟩

/-- Vector subtraction. -/
def sub (a b : CoefficientVector n' n R) : CoefficientVector n' n R :=
  ⟨Array.zipWith FMvPolynomial.sub a.vec b.vec, by simp [a.hsize, b.hsize]⟩

/-- Scale a vector by a monomial. -/
def mulMonomial (m : FMonomial n) (c : R) (v : CoefficientVector n' n R) :
    CoefficientVector n' n R :=
  ⟨v.vec.map (FMvPolynomial.mulMonomial m c), by simp [v.hsize]⟩

/-- Scale a vector by a polynomial. -/
def mul (f : FMvPolynomial n R) (v : CoefficientVector n' n R) : CoefficientVector n' n R :=
  ⟨v.vec.map (FMvPolynomial.mul f), by simp [v.hsize]⟩

/-- Compute the linear combination Σ (as[i] * bs[i]). -/
def linearCombination
    (as : Array (FMvPolynomial n R)) (bs : Array (CoefficientVector n' n R)) :
    CoefficientVector n' n R :=
  (Array.zip as bs).foldl (init := zero n' n)
    fun acc (a, b) => acc.add (b.mul a)

/-- Compute the coefficient vector of the S-polynomial of `f` and `g`. -/
def sPolynomial (ord : FMonomialOrder n)
    (f g : FMvPolynomial n R) (vf vg : CoefficientVector n' n R) :
    CoefficientVector n' n R :=
  match f.leadingTerm ord, g.leadingTerm ord with
  | some (lm_f, lc_f), some (lm_g, lc_g) =>
    let lcm := FMonomial.lcm lm_f lm_g
    let mf := (lcm.divide lm_f).getD (FMonomial.zero n)
    let mg := (lcm.divide lm_g).getD (FMonomial.zero n)
    (vf.mulMonomial mf lc_g).sub (vg.mulMonomial mg lc_f)
  | _, _ => zero n' n

end CoefficientVector

/-- Synthesize witnesses for the reduction of the S-polynomials. -/
private def synthesizeSPolyWitnesses (ord : FMonomialOrder n) (basis : Array (FMvPolynomial n R)) :
    Array (Array (Array (FMvPolynomial n R))) :=
  basis.mapIdx fun _ f =>
    basis.mapIdx fun _ g =>
      let sPolynomial    := (sPolynomial ord f g)
      let ⟨quotients, _⟩ := mvDivide ord sPolynomial basis
      quotients

/-- A Groebner basis alongside a witness. -/
structure GroebnerBasis (n : ℕ) (R : Type*) where
  basis : Array (FMvPolynomial n R)
  w : Groebner.Witness n R

def buchberger
    (ord : FMonomial n → FMonomial n → Ordering)
    (gens : Array (FMvPolynomial n R)) (fuel : ℕ := 2048) : GroebnerBasis n R :=
  let basisWithCoefficients₀ : Array (FMvPolynomial n R × CoefficientVector gens.size n R) :=
    gens.mapIdx (fun i g => (normalize g, i))
      |>.filterMap fun (g, i) =>
        -- `mapIdx` doesn't give us that i < gens.size, even though it ought to hold, so we'll
        -- reestablish this invariant.
        if h : i < gens.size then
          if g.size > 0 then
            some (g, CoefficientVector.unit gens.size n ⟨i, h⟩)
          else
            none
        else
          none
  let queue₀ : List (ℕ × ℕ) :=
    (List.range basisWithCoefficients₀.size).foldl
      (fun pairs j => pairs ++ (List.range j).map (fun i => (i, j)))
      []
  -- Compute the basis and extract the witnesses.
  let basisWithCoefficients := loop fuel basisWithCoefficients₀ queue₀
  let basis := basisWithCoefficients.map Prod.fst
  ⟨basis, {
    bm := basisWithCoefficients.map (·.2.vec),
    sr := synthesizeSPolyWitnesses ord basis
  }⟩
where
  /-- Process one pair `(i, j)` and return the updated basis/coefficients and remaining queue. -/
  loopOne
      (basisWithCoefficients : Array (FMvPolynomial n R × CoefficientVector gens.size n R))
      (queue : List (ℕ × ℕ))
      (i j : ℕ) :
      Array (FMvPolynomial n R × CoefficientVector gens.size n R) × List (ℕ × ℕ) :=
    match basisWithCoefficients[i]?, basisWithCoefficients[j]? with
    | none, _
    | _, none                    => (basisWithCoefficients, queue)
    | some (f, vf), some (g, vg) =>
      match f[0]?, g[0]? with
      | none, _
      | _, none                      => (basisWithCoefficients, queue)
      | some (lm_f, _), some (lm_g, _) =>
        -- As previously, if the leading monomials are relatively prime, the reduction is automatic.
        if FMonomial.relativelyPrime? lm_f lm_g then
          (basisWithCoefficients, queue)
        else
          let basis   := basisWithCoefficients.map Prod.fst
          let (qs, r) := mvDivide ord (sPolynomial ord f g) basis
          if r.size == 0 then
            (basisWithCoefficients, queue)
          else
            let i      := basisWithCoefficients.size
            let queue₁ := queue ++ (List.range i).map (·, i)
            -- Express the remainder as a linear combination of the generators.
            let vr := (CoefficientVector.sPolynomial ord f g vf vg).sub
              (CoefficientVector.linearCombination qs (basisWithCoefficients.map Prod.snd))
            (basisWithCoefficients.push (r, vr), queue₁)
  /-- Iterate through the queue until fuel is exhausted or the queue is empty. -/
  loop (fuel : ℕ)
      (basisWithCoefficients : Array (FMvPolynomial n R × CoefficientVector gens.size n R))
      (queue : List (ℕ × ℕ)) :
      Array (FMvPolynomial n R × CoefficientVector gens.size n R) :=
    match fuel with
    | 0     => basisWithCoefficients
    | n + 1 =>
      match queue with
      | []               => basisWithCoefficients
      | (i, j) :: queue' =>
        let (basisWithCoefficients₁, queue₁) := loopOne basisWithCoefficients queue' i j
        loop n basisWithCoefficients₁ queue₁

end Certification

end FMvPolynomial
