import Fettuccine.Algorithm.Divide

/-!
# Buchberger's Algorithm

This file implements Buchberger's algorithm for the computation of Gröbner bases of ideals of
`FMvPolynomial n R`.

## Definitions

* `buchberger ord gens (fuel)` : computes a Gröbner basis for the ideal generated by `gens` with
  respect to the monomial order `ord`, constrained by `fuel` (default: 2048).
-/

namespace FMonomial

/-- Two monomials are said to be **relatively prime** if they share no common variables with
    positive exponents. -/
def relativelyPrime? (m₁ m₂ : FMonomial n) : Bool :=
  Id.run do
    for i in [:n] do
      let a := m₁.data.getD i 0
      let b := m₂.data.getD i 0
      if !(a == 0 || b == 0) then
        return false
    return true

end FMonomial

namespace FMvPolynomial

variable {n : ℕ}
variable {R : Type*} [DecidableEq R] [Zero R] [AddGroup R] [DivisionRing R]

/-- The **S-polynomial** of two (non-zero) polynomials `f` and `g` with respect to the monomial
    order `ord`. -/
-- S(f, g) = (l / lm_f) * lc_g * f - (l / lm_g) * lc_f * g
--         = lcm(lm_f, lm_g) / lm_f * lc_g * f - lcm(lm_f, lm_g) / lm_g * lc_f * g
def sPolynomial (ord : FMonomial n → FMonomial n → Ordering) (f g : FMvPolynomial n R)
    : FMvPolynomial n R :=
  match f[0]?, g[0]? with
  | some (lm_f, lc_f), some (lm_g, lc_g) =>
    -- These divisions necessarily always succeed because the lowest common multiple is
    -- definitionally divisible by both.
    let lcm := FMonomial.lcm lm_f lm_g
    let mf := (lcm.divide lm_f).getD (FMonomial.zero n)
    let mg := (lcm.divide lm_g).getD (FMonomial.zero n)
    sub ord (mulMonomial ord mf lc_g f) (mulMonomial ord mg lc_f g)
  | _, _ =>
    -- If either polynomial is zero, the S-polynomial is conventionally taken to be zero. (This
    -- generally doesn't come up in practice.)
    FMvPolynomial.zero

/-- **Buchberger's algorithm** for computing a Gröbner basis, uncertified. -/
def buchberger (ord : FMonomial n → FMonomial n → Ordering) (gens : Array (FMvPolynomial n R))
    -- Again, this should be enough fuel.
    (fuel : ℕ := 2048) : Array (FMvPolynomial n R) :=
  -- Initially, the basis consists of the (non-zero) generators and we consider each pair.
  let basis₀ : Array (FMvPolynomial n R) :=
    (gens.map (normalize ord)).filter fun g => g.size > 0
  let queue₀ : List (ℕ × ℕ) :=
    (List.range basis₀.size).foldl
      (fun pairs j => pairs ++ (List.range j).map (fun i => (i, j)))
      []
  loop fuel basis₀ queue₀
where
  /-- Process one pair `(i, j)` and return the updated basis and remaining queue. -/
  loopOne (basis : Array (FMvPolynomial n R)) (queue : List (ℕ × ℕ)) (i j : Nat) :
      Array (FMvPolynomial n R) × List (ℕ × ℕ) :=
    match basis[i]?, basis[j]? with
    | none, _
    | _, none        => (basis, queue)
    | some f, some g =>
      match f[0]?, g[0]? with
      | none, _
      | _, none                      => (basis, queue)
      | some (lmf, _), some (lmg, _) =>
        if FMonomial.relativelyPrime? lmf lmg then
          -- If the leading monomials are relatively prime, the S-polynomial automatically reduces
          -- to zero regardless of the monomial order.
          (basis, queue)
        else
          let (_, r) := mvDivide ord (sPolynomial ord f g) basis
          if r.size == 0 then
            (basis, queue)
          else
            let queue₁ := queue ++ (List.range basis.size).map (·, basis.size)
            (basis.push r, queue₁)
  /-- Iterate through the queue until fuel is exhausted or the queue is empty. -/
  loop (fuel : ℕ) (basis : Array (FMvPolynomial n R)) (queue : List (ℕ × ℕ)) :
      Array (FMvPolynomial n R) :=
    match fuel with
    | 0        => basis -- probably wrong
    | fuel + 1 =>
      match queue with
      | []               => basis -- done
      | (i, j) :: queue' =>
        let (basis₁, queue₁) := loopOne basis queue' i j
        loop fuel basis₁ queue₁

section Certification



end Certification

end FMvPolynomial
