import Fettuccine.Algorithm.Divide

/-!
# Buchberger's Algorithm

This file implements Buchberger's algorithm for the computation of Gröbner bases of ideals of
`CMvPolynomial n R`.

## Definitions

* `buchberger ord gens fuel` : computes a Gröbner basis for the ideal generated by `gens` with
  respect to the monomial order `ord`, constrained by `fuel`.
-/

namespace CMonomial

/-- Two monomials are said to be **relatively prime** if they share no common variables with
    positive exponents. -/
def relativelyPrime? (m₁ m₂ : CMonomial n) : Bool :=
  Id.run do
    for i in [:n] do
      let a := m₁.data.getD i 0
      let b := m₂.data.getD i 0
      if !(a == 0 || b == 0) then
        return false
    return true

end CMonomial

namespace CMvPolynomial

variable {n : ℕ}
variable {R : Type*} [DecidableEq R] [Zero R] [AddGroup R] [DivisionRing R]

/-- The **S-polynomial** of two (non-zero) polynomials `f` and `g` with respect to the monomial
    order `ord`. -/
-- S(f, g) = (l / lm_f) * lc_g * f - (l / lm_g) * lc_f * g
--         = lcm(lm_f, lm_g) / lm_f * lc_g * f - lcm(lm_f, lm_g) / lm_g * lc_f * g
def sPolynomial (ord : CMonomial n → CMonomial n → Ordering) (f g : CMvPolynomial n R)
    : CMvPolynomial n R :=
  match f[0]?, g[0]? with
  | some (lm_f, lc_f), some (lm_g, lc_g) =>
    -- These divisions necessarily always succeed because the lowest common multiple is
    -- definitionally divisible by both.
    let lcm := CMonomial.lcm lm_f lm_g
    let mf := (lcm.divide lm_f).getD (CMonomial.zero n)
    let mg := (lcm.divide lm_g).getD (CMonomial.zero n)
    sub ord (mulMonomial ord mf lc_g f) (mulMonomial ord mg lc_f g)
  | _, _ =>
    -- If either polynomial is zero, the S-polynomial is conventionally taken to be zero. (This
    -- generally doesn't come up in practice.)
    CMvPolynomial.zero

/-- **Buchberger's algorithm** for computing a Gröbner basis. -/
def buchberger (ord : CMonomial n → CMonomial n → Ordering) (gens : Array (CMvPolynomial n R))
    -- Again, this should be enough fuel.
    (fuel : ℕ := 2048) : Array (CMvPolynomial n R) :=
  loop fuel ord basis₀ pairs₀ 0
where
  -- Initially, the basis consists of the (non-zero) generators and we consider each pair.
  basis₀ : Array (CMvPolynomial n R) :=
    (gens.map (normalize ord)).filter fun g => g.size > 0
  pairs₀ : Array (ℕ × ℕ) :=
    Id.run do
      let mut pairs : Array (ℕ × ℕ) := #[]
      for j in [:basis₀.size] do
        for i in [:j] do
          pairs := pairs.push (i, j)
      return pairs
  -- Each time we are forced to extend our basis, we must consider the pairs it forms with existing
  -- basis elements.
  ext.pairs (pairs : Array (ℕ × ℕ)) (i' : Nat) : Array (ℕ × ℕ) :=
    Id.run do
      let mut pairs' := pairs
      for k in [:i'] do
        pairs' := pairs'.push (k, i')
      return pairs'
  /-- Process one pair from the pair queue at cursor `ptr`. -/
  checkOne (ord : CMonomial n → CMonomial n → Ordering)
      (basis : Array (CMvPolynomial n R)) (pairs : Array (ℕ × ℕ)) (ptr i j : Nat) :
      Array (CMvPolynomial n R) × Array (ℕ × ℕ) × Nat :=
    match basis[i]?, basis[j]? with
    | none, _
    | _, none        => (basis, pairs, ptr + 1)
    | some f, some g =>
      match f[0]?, g[0]? with
      | none, _
      | _, none                      => (basis, pairs, ptr + 1)
      | some (lmf, _), some (lmg, _) =>
        if lmf.relativelyPrime? lmg then
          -- If the leading monomials are relatively prime, the S-polynomial automatically reduces
          -- to zero regardless of the monomial order.
          (basis, pairs, ptr + 1)
        else
          let (_, r) := mvDivide ord (sPolynomial ord f g) basis
          if r.size == 0 then
            (basis, pairs, ptr + 1)
          else
            let basis' := basis.push r
            let pairs' := ext.pairs pairs basis.size
            (basis', pairs', ptr + 1)
  /-- Iterate through the pair queue by cursor `ptr` until fuel is exhausted or queue ends. -/
  loop (fuel : ℕ) (ord : CMonomial n → CMonomial n → Ordering)
      (basis : Array (CMvPolynomial n R)) (pairs : Array (ℕ × ℕ)) (ptr : Nat) :
      Array (CMvPolynomial n R) :=
    match fuel with
    | 0        => basis
    | fuel + 1 =>
      match pairs[ptr]? with
      | none        => basis
      | some (i, j) =>
        let (basis', pairs', ptr') := checkOne ord basis pairs ptr i j
        loop fuel ord basis' pairs' ptr'

end CMvPolynomial
